import React from "react";
import Head from "next/head";

import classes from "./Layout.module.css";

import Navbar from "../Navbar/Navbar";

const Layout = (props) => {
  return (
    <div className={classes.Body}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={classes.Main}>{props.children}</main>
    </div>
  );
};
export default Layout;
